stages:
- security
- lint
- build

security:
  stage: security
  script:
  - npm audit

codestyle:
  stage: lint
  script:
  - export PYTHON=/usr/local/bin/python2.7
  - npm ci
  - npm run lint

build:
  stage: build
  script:
  - export PYTHON=/usr/local/bin/python2.7
  - npm ci
